# Generated by Django 3.2.5 on 2021-10-15 06:47

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.PositiveIntegerField(default=1, verbose_name='ユニット')),
                ('question1', models.CharField(choices=[('a', '学院はどこですか？'), ('b', '部活・サークルは？'), ('c', '出身県はどこですか？'), ('d', '出身高校はどこですか？'), ('e', '興味のある分野はなんですか？'), ('f', '将来の夢はなんですか？')], max_length=1)),
                ('question2', models.CharField(choices=[('a', '学院はどこですか？'), ('b', '部活・サークルは？'), ('c', '出身県はどこですか？'), ('d', '出身高校はどこですか？'), ('e', '興味のある分野はなんですか？'), ('f', '将来の夢はなんですか？')], max_length=1)),
                ('question3', models.CharField(choices=[('a', '学院はどこですか？'), ('b', '部活・サークルは？'), ('c', '出身県はどこですか？'), ('d', '出身高校はどこですか？'), ('e', '興味のある分野はなんですか？'), ('f', '将来の夢はなんですか？')], max_length=1)),
                ('Monday', models.BooleanField(default=False, verbose_name='Monday')),
                ('Tuesday', models.BooleanField(default=False, verbose_name='Tuesday')),
                ('Wednesday', models.BooleanField(default=False, verbose_name='Wednesday')),
                ('Thursday', models.BooleanField(default=False, verbose_name='Thursday')),
                ('Friday', models.BooleanField(default=False, verbose_name='Friday')),
                ('Saturday', models.BooleanField(default=False, verbose_name='Saturday')),
                ('Sunday', models.BooleanField(default=False, verbose_name='Sunday')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='プロフィール写真')),
                ('nickname', models.TextField(max_length=20, verbose_name='ニックネーム')),
                ('comment', models.TextField(max_length=50, null=True, verbose_name='ひとことコメント')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
