# Generated by Django 3.2.5 on 2021-10-18 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_profilesetting_profilecreate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileCreate',
            new_name='Profile',
        ),
    ]
